export const GET_ALLCOUNTRIES = 'GET_ALLCOUNTRIES';
export const POST_ALLACTIVITIES = 'POST_ALLACTIVITIES';
export const GETCOUNTRYBYID = 'GETCOUNTRYBYID';
export const GETCOUNTRYBYNAME = 'GETCOUNTRYBYNAME'

export const FILTERBYCONTINENT = 'FILTERBYCONTINENT';
export const FILTERBYACTIVITY = 'FILTERBYACTIVITY';

export const ORDENBYASCDSC = 'ORDENBYASCDSC';
export const ORDENBYPOPULATION = 'ORDENBYPOPULATION';

export const DELETEACTIVITY = 'DELETEACTIVITY';